// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: gRPC-server/proto/notes.proto

package notepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NoteText      string                 `protobuf:"bytes,2,opt,name=note_text,json=noteText,proto3" json:"note_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNoteRequest) Reset() {
	*x = CreateNoteRequest{}
	mi := &file_gRPC_server_proto_notes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNoteRequest) ProtoMessage() {}

func (x *CreateNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_server_proto_notes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNoteRequest.ProtoReflect.Descriptor instead.
func (*CreateNoteRequest) Descriptor() ([]byte, []int) {
	return file_gRPC_server_proto_notes_proto_rawDescGZIP(), []int{0}
}

func (x *CreateNoteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateNoteRequest) GetNoteText() string {
	if x != nil {
		return x.NoteText
	}
	return ""
}

type CreateNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoteId        string                 `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNoteResponse) Reset() {
	*x = CreateNoteResponse{}
	mi := &file_gRPC_server_proto_notes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNoteResponse) ProtoMessage() {}

func (x *CreateNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gRPC_server_proto_notes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNoteResponse.ProtoReflect.Descriptor instead.
func (*CreateNoteResponse) Descriptor() ([]byte, []int) {
	return file_gRPC_server_proto_notes_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNoteResponse) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

var File_gRPC_server_proto_notes_proto protoreflect.FileDescriptor

const file_gRPC_server_proto_notes_proto_rawDesc = "" +
	"\n" +
	"\x1dgRPC-server/proto/notes.proto\x12\x04note\"I\n" +
	"\x11CreateNoteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tnote_text\x18\x02 \x01(\tR\bnoteText\"-\n" +
	"\x12CreateNoteResponse\x12\x17\n" +
	"\anote_id\x18\x01 \x01(\tR\x06noteId2P\n" +
	"\vNoteService\x12A\n" +
	"\n" +
	"CreateNote\x12\x17.note.CreateNoteRequest\x1a\x18.note.CreateNoteResponse\"\x00B\x1cZ\x1a./gRPC-server/proto;notepbb\x06proto3"

var (
	file_gRPC_server_proto_notes_proto_rawDescOnce sync.Once
	file_gRPC_server_proto_notes_proto_rawDescData []byte
)

func file_gRPC_server_proto_notes_proto_rawDescGZIP() []byte {
	file_gRPC_server_proto_notes_proto_rawDescOnce.Do(func() {
		file_gRPC_server_proto_notes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gRPC_server_proto_notes_proto_rawDesc), len(file_gRPC_server_proto_notes_proto_rawDesc)))
	})
	return file_gRPC_server_proto_notes_proto_rawDescData
}

var file_gRPC_server_proto_notes_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gRPC_server_proto_notes_proto_goTypes = []any{
	(*CreateNoteRequest)(nil),  // 0: note.CreateNoteRequest
	(*CreateNoteResponse)(nil), // 1: note.CreateNoteResponse
}
var file_gRPC_server_proto_notes_proto_depIdxs = []int32{
	0, // 0: note.NoteService.CreateNote:input_type -> note.CreateNoteRequest
	1, // 1: note.NoteService.CreateNote:output_type -> note.CreateNoteResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gRPC_server_proto_notes_proto_init() }
func file_gRPC_server_proto_notes_proto_init() {
	if File_gRPC_server_proto_notes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gRPC_server_proto_notes_proto_rawDesc), len(file_gRPC_server_proto_notes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gRPC_server_proto_notes_proto_goTypes,
		DependencyIndexes: file_gRPC_server_proto_notes_proto_depIdxs,
		MessageInfos:      file_gRPC_server_proto_notes_proto_msgTypes,
	}.Build()
	File_gRPC_server_proto_notes_proto = out.File
	file_gRPC_server_proto_notes_proto_goTypes = nil
	file_gRPC_server_proto_notes_proto_depIdxs = nil
}
